export interface Item{
  currentPage: number
  total: number
  totalPages: number
  pageSize: number
  products: Product[]
  lastSearchDate: string
  relatedQueries: any
  sscs: any
  relatedCategories: any
  resources: any
  redirectUrl: any
  promotions: any
  hasBrandStore: boolean
  productStatusCode: any
  sscStatusCode: any
  indexName: string
  queryId: string
  Brand: string
  breadcrumb: any
}

export interface Product {
  sku: string
  name: string
  shortDescription: string
  customerRating: number
  customerRatingCount: number
  customerReviewCount: number
  productUrl: string
  currentRegion: string
  hideSavings: boolean
  hideSaleEndDate: boolean
  productType: any
  regularPrice: number
  salePrice: number
  saleEndDate?: number
  thumbnailImage: string
  primaryParentCategoryId: string
  categoryName: string
  ehf: number
  seoText: string
  sellerId: any
  seller: any
  highResImage?: string
  altLangSeoText: any
  offerId: any
  priceUnit: string
  requiresAgeVerification: boolean
  isPriceEndsLabel: boolean
  hasPromotion: boolean
  isAdvertised: boolean
  isClearance: boolean
  isInStoreOnly: boolean
  isOnlineOnly: boolean
  isVisible: boolean
  isPreorderable: boolean
  isFrenchCompliant: boolean
  isMarketplace: boolean
  hasFrenchContent: boolean
  categoryIds: string[]
}
